// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPeAeISiZfSFPxLqNORQ6kwrj0SN7H7-Q',
    appId: '1:166014259575:web:5038fb87a69f621b435172',
    messagingSenderId: '166014259575',
    projectId: 'melodic-metrics-332419',
    authDomain: 'melodic-metrics-332419.firebaseapp.com',
    databaseURL: 'https://melodic-metrics-332419-default-rtdb.firebaseio.com',
    storageBucket: 'melodic-metrics-332419.appspot.com',
    measurementId: 'G-WYVMVX26NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQQp0dISV-MnH6oGtYGD_tYXKagAdW12g',
    appId: '1:166014259575:android:ed9ef2709b65c681435172',
    messagingSenderId: '166014259575',
    projectId: 'melodic-metrics-332419',
    databaseURL: 'https://melodic-metrics-332419-default-rtdb.firebaseio.com',
    storageBucket: 'melodic-metrics-332419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Ss7XWToznzOMXgx4SRbSZ9xMKr7ziw4',
    appId: '1:166014259575:ios:7a51bd8fb6cb0f2f435172',
    messagingSenderId: '166014259575',
    projectId: 'melodic-metrics-332419',
    databaseURL: 'https://melodic-metrics-332419-default-rtdb.firebaseio.com',
    storageBucket: 'melodic-metrics-332419.appspot.com',
    iosClientId: '166014259575-sfnum94g5q6d4k0ntnq8v741e7da0fg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Ss7XWToznzOMXgx4SRbSZ9xMKr7ziw4',
    appId: '1:166014259575:ios:e79f134e6d7c73a8435172',
    messagingSenderId: '166014259575',
    projectId: 'melodic-metrics-332419',
    databaseURL: 'https://melodic-metrics-332419-default-rtdb.firebaseio.com',
    storageBucket: 'melodic-metrics-332419.appspot.com',
    iosClientId: '166014259575-hitfomsbillfkpr7lgea0v62b0e6k7m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
